version: '3'
services:
  frontend:
    build: ./front
    ports:
      - "3001:3000"
    

  backend:
    build: ./my-api
    tty: true
    restart: unless-stopped
    environment:
      - RELUTION_PRERUN_SCRIPT=/opt/selfsigned/trust_selfsigned.sh=value
    ports:
      - "80:80"
      

  database:
    build: ./baza
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_USER: "dusan"
      MYSQL_PASSWORD: "dusan"
      MYSQL_DATABASE: "todo2"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


  

