version: '3.8'

services:
  backend:
    build:
      context: ./my-api
      dockerfile: dockerfile
    environment:
      DB_HOST: database
      DB_DATABASE: todo2
      DB_USERNAME: root
      DB_PASSWORD: dusan
    depends_on:
      - database
    ports:
      - "8000:80"

  database:
    image: mysql
    environment:
      MYSQL_DATABASE: todo2
      MYSQL_ROOT_PASSWORD: dusan
    ports:
      - "3307:3306"

  

  frontend:
    build:
      context: ./front
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data:

