version: '3'
services:
  frontend:
    build: ./front
    ports:
      - "3000:3000"

  backend:
    build: ./api
    ports:
      - "80:80"

  database:
    build: ./baza
    environment:
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local