FROM php:8.2-apache
WORKDIR /usr/src/myapp
COPY . /usr/src/myapp

RUN apt-get update && \
    apt-get install -y \
	libzip-dev \
	zip
RUN a2enmode rewrite
RUN docker-php-ext-install pdo_mysql zip
#ENV APACHE_DOCUMENT_ROOT= /var/www/html/public
CMD [ "php", "./routes/api.php" ]
