FROM php
WORKDIR /usr/src/myapp
COPY . /usr/src/myapp
CMD [ "php", "./index.php" ]
RUN apt-get update && apt-get install -y \
		libfreetype-dev \
		libjpeg62-turbo-dev \
		libpng-dev \
	&& docker-php-ext-configure gd --with-freetype --with-jpeg \
	&& docker-php-ext-install -j$(nproc) gd
  FROM php:8.2-cli
RUN docker-php-source extract \
	# do important things \
	&& docker-php-source delete
